### ISSUE TITLE
Let enter key press send data inside of button press

### ISSUE THREAD

**Issue by gabkdejesus** [Quillot/TabSafe#1]
Users might prefer pressing enter over clicking save.

**Comment by Quillot** [comment]
Solved as of [commit 4](https://github.com/Quillot/TabSafe/commit/824f40e160cd146e6ad938e3f56a60bb3da3352a)

**Comment by gabkdejesus** [comment]
Solved as of [commit 4](https://github.com/Quillot/TabSafe/commit/824f40e160cd146e6ad938e3f56a60bb3da3352a)
